-- Create a table for storing mailing list emails
create table mailing_list (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table mailing_list enable row level security;

-- Create a policy to allow anyone to insert their email (for public sign-up)
create policy "Enable insert for everyone" on mailing_list
  for insert with check (true);

-- Create a policy to allow only authenticated users (admins) to view the list
-- Assuming you might want to view this in the dashboard or a future admin page
create policy "Enable read access for authenticated users only" on mailing_list
  for select using (auth.role() = 'authenticated');


